[target.x86_64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile.x86_64"

[target.i686-unknown-linux-gnu]
dockerfile = "cross/Dockerfile.i686"

[target.aarch64-unknown-linux-gnu]
dockerfile = "cross/Dockerfile.aarch64"
